### PR TITLE
feat: add shared element transitions

### PR DESCRIPTION
**Pull request by WoLewicki**
## Description

PR adding shared element transitions to `native-stack`. Please consider a draft for now since there is no `Android` implementation and only basic examples work on `iOS`. Most of the code is based on the shared element transitions in [`react-native-navigation`](https://github.com/wix/react-native-navigation) since it also uses `UIViewController` as a container of the screen.

## Test code and steps to reproduce

`Test1089.tsx`

## Checklist

- [x] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Updated documentation: 
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/guides/GUIDE_FOR_LIBRARY_AUTHORS.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/native-stack/README.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/createNativeStackNavigator/README.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/src/types.tsx
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/src/native-stack/types.tsx
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by nandorojo** [comment]
Can't wait for this!

**Comment by WoLewicki** [comment]
We are working on coupling SET platform specifics with `reanimated` ability to animate all view's props. You can watch the progress [here](https://github.com/software-mansion/react-native-reanimated/pull/2561) and [here](https://github.com/software-mansion/react-native-screens/tree/%40wolewicki/shared-elements-with-rea). We are planning to prioritize it in the next days.

**Comment by nandorojo** [comment]
That’s amazing news. You guys continue to innovate!

**Comment by hirbod** [comment]
That is indeed amazing news!

**Comment by nandorojo** [comment]
As an update from my end, I did manage to get layout animation working on Web, so once this works on native, I should be able to add cross-platform support to Moti.

**Comment by nandorojo** [comment]
> I believe SETs are working great right now

Do they work for you? I can never seem to get them working properly.

**Comment by tboba** [comment]
@nandorojo I mean, they are still in the _experimental_ state, but the whole logic for making screens work is being swizzled in the Reanimated - I don't think we need that PR anymore 🤔
I have also saw some of the stories from users on X (e.g. https://twitter.com/alihdjr/status/1755531153119887769) with the working apps with SETs onboard. I'm not the expert in area of Reanimated though 😄

**Comment by WoLewicki** [comment]
Yeah, this PR is no longer necessary since we went in the direction of connecting it with `react-native-reanimated`. I'll close this PR then.

**Pull request closed without merging**
