### PR TITLE
Ensure header elements are visible on iOS

### PR DESCRIPTION
**Pull request by zibs**
Adds ensureHeaderButtonsVisible method in RNScreens.m
References issues #432 and #528.
References and incorporates PR #644 as well

Thanks @WoLewicki!

### CODE REVIEW

**Comment by WoLewicki** [comment]
Thanks for submitting the PR! The main problem with this method is that it assumes that 0.1-second time is enough for the buttons to align correctly after it. It may be not true for screens with more content in them or slower phones. You can see https://github.com/software-mansion/react-native-screens/issues/528#issuecomment-694829190. Is it available for you to check if this 0.1-second time is always enough for this to work correctly?

**Comment by zibs** [comment]
I can get back to you on this this week. It seems like after testing in the wild that 0.1 wasn't enough time when running CPU heavy transitions.

**Comment by zibs** [comment]
So I see here that I've left it set at `0.5`, which might even be too much. In production we're running it at `0.2` and don't think we've had any issues since. Want me to increase it to `0.2` here? Or just leave it at `0.5`?

Other than that it should be good to go.

**Comment by WoLewicki** [comment]
I am not sure if we will want to merge it for now. It is very much a workaround, and with some randomness included, so I would be very hesitant about doing so. I will ping here when it is clear if we want to do it. And for now, I think you can leave it as it is :tada:

**Comment by casperstr** [comment]
What is the status on this? Can I do anything to help move this forward?

**Comment by WoLewicki** [comment]
@casperstr see my comment above. I don't think there is much more to be done about it. If someone wants to use it, he should patch-package it for now. I think we would need a deterministic solution in order to merge such a change.

**Comment by casperstr** [comment]
> @casperstr see my comment above. I don't think there is much more to be done about it. If someone wants to use it, he should patch-package it for now. I think we would need a deterministic solution in order to merge such a change.

The native stack is currently unusable if header buttons are required. Do we have any path forward to patch this with a deterministic solution?

**Comment by WoLewicki** [comment]
I haven't found any other solution unfortunately, but I am open to contributions regarding this.

**Comment by abram** [comment]
Hi @zibs, thanks for your work here. I ran into this issue today and I was grateful to find this PR and discussion. @WoLewicki, I've submitted PR #902 containing a solution I came up with. Hope it's helpful!

**Pull request closed without merging**
