### PR TITLE
remove unused imports and add Component from React in Example Folder!.

### PR DESCRIPTION
**Pull request by luism3861**
this PR remove unused imports and add `Component` from React in Example Folder!.

### CODE REVIEW

**Comment by WoLewicki** [comment]
Thanks for your contribution! Maybe you would like to rewrite these views to functional API instead of classes? It would enable users to test e.g. hooks with new navigation events.

**Comment by luism3861** [comment]
> Thanks for your contribution! Maybe you would like to rewrite these views to functional API instead of classes? It would enable users to test e.g. hooks with new navigation events.

of course i would like to work with rewrite all files with functional API.!

**Comment by WoLewicki** [comment]
I think we can close this PR in favor of the one with functional API, am I right?

**Comment by luism3861** [comment]
> I think we can close this PR in favor of the one with functional API, am I right?

yep you're right

**Comment by luism3861** [comment]
@WoLewicki  yup you're right

**Pull request closed without merging**
