### PR TITLE
fix: containedTransparentModal swipe back gesture issue

### PR DESCRIPTION
**Pull request by hurali97**
## Description
This PR aims to fix the gesture issue on the modal presentation 'containedTransparentModal'. The issue is raised here: https://github.com/software-mansion/react-native-screens/issues/1476#issue-1268853334

So if we look at the video attached in the above issue, we'd see the swipe back gesture works (which it shouldn't) when the presentations type is 'containedTransparentModal' and it doesn't work(excellent) when the presentation type is 'transparentModal'. 

## Changes
The method `gestureRecognizerShouldBegin` is checking for `topScreen` but not for the `topModal`, and ideally it should check for it. So the idea is to compare the `topModal` is presented by the `topScreen` and if yes, we obscure the gesture and return `NO`. And obviously, if the topModal isn't being presented we check for `isAttached`  flag to let the gestures flow.
Relevant  changes: https://github.com/software-mansion/react-native-screens/commit/15fb9dde775f3ca2aaa24783c80b978a27fbfba0

### Before (This Before video is taken from the issue link provided above)
https://user-images.githubusercontent.com/47336142/177417997-bed07337-f101-4113-b05c-ae7f0e0953fc.mp4

### After
https://user-images.githubusercontent.com/47336142/177416558-03b6ab36-265b-49d6-9b95-9641a83b1344.mp4

## Test code and steps to reproduce
The code is taken from here and added in TestExample dir, below is the repro provided by the issue opener.
https://github.com/NguyenHoangMinhkkkk/navigation-reproduce

Comment out the below fixes, `pod install` and rebuild the TestExample iOS project and you should be able to repro.
https://github.com/software-mansion/react-native-screens/commit/15fb9dde775f3ca2aaa24783c80b978a27fbfba0

## Checklist

- [x] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Updated documentation: 
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/guides/GUIDE_FOR_LIBRARY_AUTHORS.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/native-stack/README.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/src/types.tsx
  - [ ] https://github.com/software-mansion/react-native-screens/blob/main/src/native-stack/types.tsx
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by hurali97** [comment]
@kkafar or anyone would want to review 👍

**Review by kkafar — COMMENTED** [review]
Thank you for your contribution!

Gesture recogniser logic received overhaul recently: 
* https://github.com/software-mansion/react-native-screens/pull/1512
* https://github.com/software-mansion/react-native-screens/pull/1516

So this PR needs to be updated & conform to the new business logic.

I will also need your to revert the changes in Podfile.lock, remove commented out code, and possibly add empty lines at file ends (you can see it easliy on github overview).

I'll come back shortly to review the changes from the perspective of business logic

**Comment by hurali97** [comment]
> Thank you for your contribution!
> 
> Gesture recogniser logic received overhaul recently:
> 
> * #1512
> * #1516
> 
> So this PR needs to be updated & conform to the new business logic.
> 
> I will also need your to revert the changes in Podfile.lock, remove commented out code, and possibly add empty lines at file ends (you can see it easliy on github overview).
> 
> I'll come back shortly to review the changes from the perspective of business logic

Hey, I incorporated to the required changes. Prevented the sending of events to RNSPanGestureRecognizer if the modal is opened. Tested the updated changes on the Test1072, doesn't break it either.

Also, regarding the empty lines, git preview seems to truncates the empty lines at bottom.

**Comment by kkafar** [comment]
Hi @hurali97,
it seems that #1476 is fixed by #1509. I used your test example in #1509 (and made a typo while adding you as co-author) 🤦🏻 . Could you confirm that it also works for you when you use screens from this commit: d7d04e6338658c18d91f80475f6174c028633f61?

**Comment by kkafar** [comment]
@hurali97
Thank you for your contribution & noticing bugs :clap: For now, we decided to go with different solution: https://github.com/software-mansion/react-native-screens/pull/1521 as it does not introduce additional conditions & (hopefully) is more reliable. I would love to hear from you, if the changes introduced in #1521 finally solve the problem.

**Pull request closed without merging**
