### PR TITLE
fix: android keyboard with autofocus

### PR DESCRIPTION
**Pull request by WoLewicki**
## Description

Change the logic of preventing `Android` keyboard dismiss in views with `autofocus` prop. We now prevent the keyboard from hiding by removing the call to `clearFocus` at the beginning of fragment transition, which is the reason why the keyboard is hidden almost exactly after it is shown on the new screen.

### Before

https://user-images.githubusercontent.com/39658211/143459533-4567e146-665c-489a-b1cd-a44a7e0719a6.mov

### After

https://user-images.githubusercontent.com/39658211/143459568-086edbb2-8640-45c8-b625-246abe123998.mov

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

**Review by kmagiera — APPROVED** [review]
Looks good. Can we just change the name of `NotifyingCoordinatorLayout` to something else as its role is no longer just sending notifications as it also overrides `clearFocus` now

**Comment by hosseinmd** [comment]
This issue happen in 3.13 too.

**Comment by LarsDepuydt** [comment]
And still in 3.20

**Comment by danstepanov** [comment]
3.11.1 works but remember to close out your app and re-run the project, you'll need to run `pod install` again, prior to running iOS.

**Pull request merged**
