### PR TITLE
chore(Android): update spotless & ktlint

### PR DESCRIPTION
**Pull request by kkafar**
## Description

Encountered some errors (seems they were looking for old CMake version (3.10.2)) & decided to bump these deps as they are long overdue.

## Changes

Ktlint: 0.43 -> 1.1.1
spotless 6.11 -> 6.22

## Checklist

- [ ] Ensured that CI passes

### CODE REVIEW

**Review by tboba — APPROVED** [review]
Great changes! Can we also put an update in this PR of `distributionUrl` field in main `gradle-wrapper.properties` file, so that we could bump gradle version here as well?

**Comment by kkafar** [comment]
Will do it in separate PR

**Comment by kkafar** [comment]
besides that it is already bumped to 7.5.1

**Comment by tboba** [comment]
Yeah, I've seen that you've bumped it yesterday 😄 nevermind

**Review by kkafar — COMMENTED** [review]
I skimmed through the code to make sure whether there are no semantics changes it all seems ok.

**Pull request merged**
