### PR TITLE
Add mavenCentral in TVOSExample

### PR DESCRIPTION
**Pull request by luancurti**
## Description

Add mavenCentral in TVOSExample

## Checklist

- [ ] Included code example that can be used to test this change
- [ ] Updated TS types
- [ ] Updated documentation: 
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/guides/GUIDE_FOR_LIBRARY_AUTHORS.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/native-stack/README.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/createNativeStackNavigator/README.md
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/src/types.tsx
  - [ ] https://github.com/software-mansion/react-native-screens/blob/master/src/native-stack/types.tsx
- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by kacperkapusciak** [comment]
Hi @luancurti,
Thank you for the PR but unfortunately, I can't merge it. There are some react-native modules that still use `jcenter` and haven't migrated to `mavenCentral` yet. See this issue: https://github.com/software-mansion/react-native-screens/issues/1092

However, adding `mavenCentral` to our tvOS Example app is a good idea. Could you bring back `jcenter` and add `mavenCentral` line below in both places? 🙏 

Cheers

**Comment by luancurti** [comment]
Hi @kacperkapusciak,

That make senses!

I revert the changes in `build.gradle`

**Comment by kacperkapusciak** [comment]
@luancurti could you also bring back `jcenter()` in `TVOSExample/android/build.gradle` and leave `mavenCentral()` line below?

**Comment by luancurti** [comment]
@kacperkapusciak I think it's ok now

**Comment by kacperkapusciak** [comment]
Thank you! 🙌

**Pull request merged**
