### PR TITLE
Rename screens.native.js -> screens.js

### PR DESCRIPTION
**Pull request by osdnk**
Eslint's `import/no-unresolved` was appearing on importing `screens`. The reason was that platform-specific extensions are not well supported by eslint.

Renaming screens.native.js to screens.js does not comes with unwanted effects because on browsers it will be still fallbacking to `screens.web.js`.

### CODE REVIEW

**Comment by osdnk** [comment]
Fixes https://github.com/kmagiera/react-native-screens/issues/62

**Comment by jarvisluong** [comment]
An alternative solution that keeps the web support is to make two files screens.ios and android, then exports all from the .native.js file 🤔

**Comment by gsklee** [comment]
@kmagiera would you like to take a look? Should be a quick one.

**Comment by skleeschulte** [comment]
[Looking at the react-native docs](https://facebook.github.io/react-native/docs/platform-specific-code.html#native-specific-extensions-ie-sharing-code-with-nodejs-and-web), I think using the .native.js extension is the correct way. [This issue can be fixed by updating the eslint-config](https://github.com/kmagiera/react-native-screens/issues/62#issuecomment-495158875).

**Comment by satya164** [comment]
I usually prefer `index.native.js` and `index.js` because webpack doesn't support `.web.js` by default anymore while RN supports `.native.js` by default, so it's less configuration.

**Comment by kacperkapusciak** [comment]
@osdnk could we close this PR for being no longer relevant 2 years later?

**Pull request closed without merging**
