### PR TITLE
chore: bump Podfile.lock for example and test apps

### PR DESCRIPTION
**Pull request by maciekstosio**
## Description

Bump RNScreens version in Podfile.lock from 3.31.0-rc.1  to 3.31.1 in test and example apps.

### CODE REVIEW

**Review by kkafar — COMMENTED** [review]
I think we re fine here. Let's open this PR

**Review by tboba — COMMENTED** [review]
Have you checked if TVOSExample also needs to be updated?

**Comment by maciekstosio** [comment]
> Have you checked if TVOSExample also needs to be updated?

I did run pod install there, but it doesn't seem to help a lot.

**Review by kkafar — APPROVED** [review]
🟢

**Pull request merged**
