### PR TITLE
fix(temp, iOS): Fix missing weak linking for Xcode 15

### PR DESCRIPTION
**Pull request by tboba**
## Description

Currently it's not possible to build our example apps because of the recent changes in the newest Xcode 15.
In the changelog they're mentioning a new linter, which lacks the support of weak linking.

This PR introduces changes in Podfiles that are required to launch our example apps. They are mainly adding required flag (`-ld_classic`) that is restoring the support for the classic linter.

**This change is temporary!** We should observe and wait for the 0.72.5 patch in React Native that adds the support for classic linter inside their Podfiles.

You can check for more information about the newest changes in linter [here](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking).

## Helpful links
- https://github.com/reactwg/react-native-releases/discussions/85#discussioncomment-7043457
- https://github.com/reactwg/react-native-releases/discussions/87#discussioncomment-7043465
- https://github.com/reactwg/react-native-releases/discussions/84#discussioncomment-7043469

## Checklist

- [ ] Ensured that CI passes

### CODE REVIEW

**Comment by tboba** [comment]
@kkafar @WoLewicki Can you ensure that our example app is being correctly installed and launched on iOS 14 / iOS 16 if you're still using Xcode 14? 🙏

**Review by kkafar — APPROVED** [review]
I'm using latest XCode already.

We can have it merged in case you're working on iOS right now. If it is not the case we can wait a day or two for React Native release, then just bump RN versions in `package.json`. 

One nitpick: 

1. We could also add `-Wl` option as recommended in official workaround by apple. There is no harm in seeing linker warnings. Up to you.

**Comment by kkafar** [comment]
Hey @tboba, 0.72.5 was released. I believe we can close this PR & open new one - with bumped version of RN.

**Comment by tboba** [comment]
Hey @kkafar, let's leave this PR open for now - I'm testing RN on the newest version and unfortunately I'm still coming across the `EXC_BAD_ACCESS` error that happens during the application launch 😕
I'll be providing an updates if anything will change in this area.

**Comment by kkafar** [comment]
KK, I'll try it out soon

**Comment by tboba** [comment]
As I'm looking on building Example apps on iOS 15 it seems to be fine, also the app is being launched correctly so I assume this PR is no longer relevant.

**Pull request closed without merging**
