### PR TITLE
fix(iOS): full screen modal crash on paper

### LINKED ISSUE #2317: Navigating to a full screen modal with custom header props causes crash
### Description

On iOS, if a full-screen modal screen has a custom `headerLeft`, `headerRight`, or `headerTitle` prop, then navigating to it causes a crash after several times.

This is the error message:
> Exception thrown while executing UI block: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

I am positive that this regression was introduced somewhere after 3.32.0.

### Steps to reproduce

1. Have two screens, one being a full-screen modal
2. Add either custom `headerLeft`, `headerRight`, or `headerTitle` function.
3. Navigate to the modal and go back several times
4. Observe the crash

### Snack or a link to a repository

https://github.com/ha3/rns-fullscreen-repro

### Screens version

3.34.0

### React Native version

0.75.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 13 (iOS 15.5)

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by maksg**
## Description

Full screen modal was crashing sometimes on Paper.
Fixes #2317.

## Test code and steps to reproduce

Added `Test2317` to tests.

## Checklist

- [x] Included code example that can be used to test this change
- [ ] Ensured that CI passes

### CODE REVIEW

**Review by kkafar — COMMENTED** [review]
Hey, the code change looks sensible, however let's put some more explanation on what happens here in the PR description please. Cause when someone comes back to this PR in a month he'll have no idea why the `navctr` could be `null` there.

**Comment by kkafar** [comment]
Also, what's going on this this failing e2e CI on iOS?

**Comment by maksg** [comment]
Done

**Review by kkafar — APPROVED** [review]
I think we're good here - thanks.

I'll merge this PR once CI passes.

**Pull request merged**
