### PR TITLE
fix: android screen orientation fix

### PR DESCRIPTION
**Pull request by kacperkapusciak**
## Description
Fixes https://github.com/software-mansion/react-native-screens/issues/836 .

## Changes
- Added check for SCREEN_ORIENTATION_UNSPECIFIED

## Checklist

- [x] Ensured that CI passes

### CODE REVIEW

**Comment by misaku** [comment]
thx to help, i try many test and this solution fix the problem! ;)

**Comment by MakChan** [comment]
Is there any timeline of when this fix will be included in a release?

**Comment by WoLewicki** [comment]
This one will probably not be included in the release since there is another PR that changes the logic of applying orientation (#860) which will ideally be included in the release.

**Comment by MakChan** [comment]
Okay, that makes sense. Any idea about when that PR will be merged and released?

**Comment by WoLewicki** [comment]
Hopefully next week.

**Comment by kacperkapusciak** [comment]
Closing in favour of https://github.com/software-mansion/react-native-screens/pull/860

**Pull request closed without merging**
