### PR TITLE
fix(Android): incorrect childCount in removeViewAt when using flatlist on fabric

### LINKED ISSUE #2282: Incorrect childCount in removeViewAt
### Description

There is a bug in react-native-screens on Android when newArchEnabled=true and we have FlatLists in our screens

We attempt to remove an incorrect number of children when calling removeViewAt in SurfaceMountingManager

This seems related to the changes introduced by @WoLewicki in [2134](https://github.com/software-mansion/react-native-screens/pull/2134) as we patched these changes into a previous version of rns and this bug became immediately apparent. This was tested on rn73 & rn74 as well

Screenshot_1722864873

### Steps to reproduce

1. Press listitem1
2. Press listitem2
3. Observe crash

### Snack or a link to a repository

https://github.com/BenIrving/rnsrepro

### Screens version

3.34.0

### React Native version

0.75.0-rc.6

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by alduzy**
## Description

This PR intents to fix the crash when navigating back from a screen with FlatList on the new architecture. The crash was caused by miscalculated `childCount` of the list.
Earlier on I found out that setting the [removeClippedSubviews](https://reactnative.dev/docs/flatlist#removeclippedsubviews) option to false (defaults to true on Android) in the FlatList fixes the problem.

This PR is rather a quick fix with an extra condition, that adds simple views in place of the miscalculated ones in `startTransitionRecursive` function if there's a FlatList with `removeClippedSubviews` option set.

Fixes #2282.

## Changes

- added `Test2282.tsx` repro
- added extra condition in `startTransitionRecursive` function

## Test code and steps to reproduce

- added `Test2282.tsx` repro

## Checklist

- [x] Ensured that CI passes

### CODE REVIEW

**Review by WoLewicki — APPROVED** [review]
It's an ugly workaround but let's stick with it for now.

**Comment by lluisandreu** [comment]
Hello @kkafar, are you going to create a release soon with this fix? Thanks

**Comment by kkafar** [comment]
Planning a stable 3.35.0 in the begging of the next week. But don't hold me to it, it will be ready when it will be ready (Cyberpunk vibes unintended)

**Comment by DorianMazur** [comment]
@alduzy This fix is working for Dev builds, but for Release builds it stil throws errors:

```
getChildDrawingOrder() returned invalid index 1 (child count is 1)
```

**Pull request merged**
