### PR TITLE
fix(iOS): deprecation of RCTImageLoader fixes 

### LINKED ISSUE #415: 'React/RCTImageView.h' file not found | iOS Build Failed
**Error** - node_modules/react-native-screens/ios/**RNSScreenStackHeaderConfig.m** **'React/RCTImageView.h' file not found**

**Versions**

    "react-native-screens": "2.3.0",
    "react": "16.8.3",
    "react-native": "0.59.8",
    "react-navigation": "^3.1.2"

### PR DESCRIPTION
**Pull request by hiteshharora**
Fix #415

### CODE REVIEW

**Comment by awhelms** [comment]
Can someone review this PR and merge or suggest viable alternatives?

**Comment by hiteshharora** [comment]
is there any update on this? Our CI pipeline is broken because of this issue. If you can help us sooner that'd be great. :)

**Comment by deroke** [comment]
Any news here?  
This PR will fix my problem ❤️ 

Thanks to @hiteshharora

**Comment by WoLewicki** [comment]
Can you check if #415 happens when you create a new project with react-native version >=0.60.0? Because if not, then it seems like not an issue of the library itself.

**Comment by WoLewicki** [comment]
Closing this since I couldn't reproduce the issue mentioned in #415 (see https://github.com/software-mansion/react-native-screens/issues/415#issuecomment-676456601). If you cannot successfully make your project work, please use [patch-package](https://www.npmjs.com/package/patch-package) and apply this fix by yourself. Feel free to comment in #415 if you have any questions.

**Pull request closed without merging**
