### PR TITLE
feat(Android): add ios like `ios_from_left` slide animation 

### PR DESCRIPTION
**Pull request by chrispader**
## Description

This PR is based on https://github.com/software-mansion/react-native-screens/pull/1945 and implements the `ios` animation in the reverse direction (slide in from left to right, slide out from right to left)

## Checklist

- [x] Included code example that can be used to test this change
- [x] Updated TS types
- [x] Updated documentation: 
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/guides/GUIDE_FOR_LIBRARY_AUTHORS.md
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/native-stack/README.md
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/src/types.tsx
  - [x] https://github.com/software-mansion/react-native-screens/blob/main/src/native-stack/types.tsx
- [x] Ensured that CI passes

### CODE REVIEW

**Comment by chrispader** [comment]
We should discuss how we want to name these two "ios-like" animations. Before there was only `ios`, but now that there are two animations - one for each direction - i renamed `ios` to `ios_from_right` and created `ios_from_left`.

I feel like this is the more consistent approach, compared to the other animations that exist. This would be a breaking change for apps that currently use `ios`, and therefore would need to be communicated in a new update.

**Comment by kkafar** [comment]
Hey @chrispader, thanks a lot for a contribution 🙌🏻 I think we might want to take a backwardcompatible approach. Let's keep the old `ios` stack animation as is, and add two new: `ios_from_right` & `ios_from_left`. This way we won't break the compatibility. We can mark the `ios` one as deprecated & I'll remove it from screens 4.0. What do you think?

**Comment by chrispader** [comment]
sounds good! @kkafar

**Comment by chrispader** [comment]
Just added back the `ios` animation option. This just links to the `ios_from_right` animation on Android.

I also added a depreaction warnings to the comments for `ios` animation.

**Comment by kkafar** [comment]
Thanks @chrispader, we just waiting for me to have time to test this & I believe we can merge. Thank you!

**Review by kkafar — APPROVED** [review]
Thanks for contributing 🎉

**Pull request merged**
