### PR TITLE
feat: change condition

### PR DESCRIPTION
**Pull request by WoLewicki**
Change of condition suggested by @kmagiera.

### CODE REVIEW

**Comment by Cal-um** [comment]
@WoLewicki Here is the debugger with the frame extending below the view
Screenshot 2020-10-27 at 09 44 54

This is the same screen presented with react-native modal which does not extend below the screen.

Screenshot 2020-10-27 at 09 44 23

As per the height measured the react native modal has a smaller height. Any idea why we are getting a larger height in the react native screens presentation?

**Comment by WoLewicki** [comment]
Probably because this modal is a `RNSScreen` and we decide the height of its frame. I cannot say much more at this moment.

**Comment by artyorsh** [comment]
Coming from https://github.com/software-mansion/react-native-screens/issues/678, can confirm that works properly in scope of that issue

**Comment by WoLewicki** [comment]
Closing in favor of #712.

**Pull request closed without merging**
