### PR TITLE
fix(Android): change context while running `runOnUiQueueThread` on 0.73 with Bridgeless

### PR DESCRIPTION
**Pull request by cortinico**
## Description

I've been discussing this change with @WoLewicki.
The problem here is that you're attempting to call `runOnUiQueueThread` on the wrong Context.

## Changes

Changes the `Context` where we invoke `.runOnUiQueueThread`

## Test code and steps to reproduce

Tested against this reproducer:
https://github.com/cortinico/reproducer-rnscreens-bridgeless

## Checklist

- [x] Included code example that can be used to test this change
- [x] Ensured that CI passes

### CODE REVIEW

**Comment by WoLewicki** [comment]
Ok we'll have to check if it works in all environments, is there a possibility for this to not work correctly in e.g. brownfield app?

**Comment by cortinico** [comment]
> Ok we'll have to check if it works in all environments, is there a possibility for this to not work correctly in e.g. brownfield app?

It should work in all environments because `.applicationContext` is provided by Android and it will be a `BridgelessReactContext`.

We're also working on a fix that will be included in 0.74, which will make `context. runOnUiQueueThread` work (so this PR won't be needed anymore).
I'd still appreciate if we can review/merge this now, and potentially revert it if we land the fix

**Comment by cortinico** [comment]
@WoLewicki e2e tests are red also on main. Is the failure legit?

**Comment by tboba** [comment]
@cortinico Yeah, currently because of PR #1913 there's a problem with clicking back button on header (on Android and iOS it always acts like pressing and holding while tapping it). That's why CI is quite broken on Android, but I wouldn't worry about it, since this error is about separate problem (which should be fixed in about an hour 💪).

**Comment by cortinico** [comment]
> @cortinico Yeah, currently because of PR #1913 there's a problem with clicking back button on header (on Android and iOS it always acts like pressing and holding while tapping it). That's why CI is currently quite broken on Android, but I wouldn't worry about it, since this error is about separate problem (which should be fixed in about an hour 💪).

Ok so we can wait for it 👍 Thank you for the heads up @tboba

**Comment by cortinico** [comment]
@tboba can we restart the e2e job?

**Comment by tboba** [comment]
@cortinico Unfortunately I still haven't managed to find the root cause of the issue on CI. With @piaskowyk, we're trying to find a solution for that, please give us a little moment 🙏 If we won't find any solution by today, we could make an exception and merge this PR (after manually checking if everything's okay).

Sorry this is taking so long!

**Comment by cortinico** [comment]
> If we won't find any solution by today, we could make an exception and merge this PR (after manually checking if everything's okay).

Sure no problem 👍 I just wanted to make sure we don't forget about this one

**Comment by tboba** [comment]
Hey @cortinico, could you merge changes from main to this PR? I believe that this time CI should be green 🚀

**Review by tboba — APPROVED** [review]
I just tested these changes with our Example app as a normal and brownfield app and looks like they're working fine! LGTM! 🚀

**Comment by tboba** [comment]
I'll merge this now, but we need to remember about reverting this change after RN 0.74 will land (as mentioned above). Thanks!

**Comment by WoLewicki** [comment]
I just tested it and it seems that when using this code in new arch with or without bridgeless mode enabled, this cast `(context.applicationContext as? ReactContext)` returns `null` making the code not work at all. Could you also check it @tboba ?  😅 

Also it seems that changing it to `(context as ThemedReactContext).reactApplicationContext.runOnUiQueueThread {` makes it work. Is such code ok @cortinico ?

**Comment by cortinico** [comment]
> I just tested it and it seems that when using this code in new arch with or without bridgeless mode enabled, this cast `(context.applicationContext as? ReactContext)` returns `null` making the code not work at all

I've tested this on Bridgeless and it was working fine for me. @WoLewicki is your testing environemnt different?

**Comment by WoLewicki** [comment]
@cortinico did you try to navigate in the application? I'll try `0.74.0-rc.0` but on `0.73.4` it resolves to `null`. I tested it in our repo in `FabricTestExample` app.

**Pull request merged**
