### PR TITLE
Changed to sync commit for fragment transaction

### PR DESCRIPTION
**Pull request by anirudhagarwal365**

### CODE REVIEW

**Comment by WoLewicki** [comment]
Does it solve crashes happening in #463?

**Comment by anirudhagarwal365** [comment]
Hi @WoLewicki  
We have released our app with this change. Till now don't see any crashes but still want to wait a little to monitor. Will update here once I feel confident.

**Comment by anirudhagarwal365** [comment]
Hi @WoLewicki . Had pushed this change in our production app with this change and have not seen a single crash for onPause since. I now feel confident about the change.

**Comment by WoLewicki** [comment]
Closed in favor of #1066. Feel free to comment if something is wrong.

**Pull request closed without merging**
